### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by thosakwe** [thosakwe/dart_scripts#1]
Inside `pubspec.yaml`:

```yaml
name: foo
version: 1.0.0
dependencies:
  gyp: ^1.0.0
scripts:
  install: gyp:build && echo Done building.
  update: scripts run install
```

To expose commands, use `tool/scripts.dart`:

```dart
import 'package:grinder/grinder.dart';

@Task('foo')
foo(workingDir) {
  print 'Bar!';
}
```
